Added control scheme for 2d scenes
JonahPlusPlus/bevy_spectator pull request #5
Opened 2023-03-31 21:47 UTC by MaikoVDV

Added 'orthographic' option to SpectatorSettings. Disables mouse looking & capturing. Makes W and S control y-axis movement.
This should significantly improve the experience in 2D scenes.
Added a 2D example scene.

2023-07-21 15:51 UTC, Shatur commented
Could you update it to Bevy 0.11?

2023-07-22 17:54 UTC, MaikoVDV commented
Done!
Also, I ran into an issue in the 3D example scene where PbrBundles wouldn't display materials (they were all that beautiful pinkish purple). Might this be a problem on my end or are you experiencing something similar?

2023-07-22 18:39 UTC, Shatur commented
> Also, I ran into an issue in the 3D example scene where PbrBundles wouldn't display materials (they were all that beautiful pinkish purple). 

Thanks, fixed it in the latest master.

2023-07-22 18:40 UTC, Shatur requested changes
I'm fine with this change, minor suggestion.

2023-07-22 18:40 UTC, Shatur commented on src/lib.rs
> +            let delta_axial = if settings.orthographic { 0f32 } else { (forward - backward) * speed };
```suggestion
            let delta_axial = if settings.orthographic { 0.0 } else { (forward - backward) * speed };
```

2023-11-10 06:23 UTC, JonahPlusPlus approved these changes

2023-11-10 06:25 UTC, merged